title = "MathPlus"
gitRepoUrl = "https://github.com/iSophes/MathPlus"

classOrder = []
gitSourceBranch = "main"
changelog = true

[home]
enabled = true
includeReadme = false

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
tagline = "Improved Mathematics Library for Roblox"
favicon = ".moonwave/static/favicon.png"

organizationName = "iSophes"
projectName = "MathPlus"
url = "https://iSophes.github.io/"
baseUrl = "/mathplus/"

[footer]
style = "dark"
copyright = "Copyright © 2023 Sophie B."

