title = "MathPlus"
gitRepoUrl = "https://github.com/iSophes/MathPlus"

classOrder = []
gitSourceBranch = "main"
changelog = true

[docusaurus]
url = "https://iSophes.github.io/"
baseUrl = "/mathplus/"  
tagline = "An Improved Mathematics Library for Roblox"
favicon = "/favicon.png"

[[classOrder]]
section = "Manager"
classes = ["Initialiser"]

[[classOrder]]

section = "Classes"
classes = ["CreateTable"]

[[classOrder]]

section = "Functions"
classes = ["add", "abs", "acos"]

[navbar]
title = ""

[navbar.logo]
src = "/thumbnail.svg"

[[navbar.items]]
href = "https://dsc.gg/weirdo-world"
label = "Discord"
position = "right" 

[home]

enabled = true
includeReadme = false

[footer]
style = "dark"
copyright = "Copyright © 2023 Sophie B. Built with Moonwave and Docusaurus. Home Page inspired by Matter"